# Transactions - Data Cleaning with Python

## Importing required libraries

In [2]:
import pandas as pd

## Loading the Dataset

In [3]:
df = pd.read_csv("Intern_dataset(in) son.csv")

In [4]:
df

,Id,OrgId,TransactionTypeId,Transaction_Date,OperationStatusId,CardlNumber,PersonId,Unnamed: 7
0,531993,132,1,4/18/2023 8:10,20,NaN,101093,NaN
1,532002,132,1,4/18/2023 8:13,20,NaN,101093,NaN
2,532007,132,1,4/18/2023 8:18,20,NaN,101093,NaN
3,532012,132,1,4/18/2023 8:19,20,NaN,101093,NaN
4,532013,21,1,4/18/2023 8:19,20,NaN,1749567,NaN
...,...,...,...,...,...,...,...,...
999995,7564988,49,2,8/16/2024 10:01,10,1FD1A6C0CC6FF437000000471736,1226287,NaN
999996,7565005,49,2,8/16/2024 10:02,10,1FD1A6C0CC6FF4370000004CABE6,1971593,NaN
999997,7565011,79,1,8/16/2024 10:02,10,1FD1A6C0CC6FF43700000034E4EF,1523555,NaN
999998,7565055,104,1,8/16/2024 10:03,10,1FD1A6C0CC6FF4370000004D15D0,851270,NaN
999999,7565057,49,2,8/16/2024 10:03,10,1FD1A6C0CC6FF437000000453BC8,3478,NaN

## Removing unnecessary columns

In [5]:
df = df.drop(columns=['Unnamed: 7'])

## Checking the data types

In [6]:
df.dtypes

Id                    int64
OrgId                 int64
TransactionTypeId     int64
Transaction_Date     object
OperationStatusId     int64
CardlNumber          object
PersonId              int64
dtype: object

## Checking for Duplicate Records

In [7]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [Id, OrgId, TransactionTypeId, Transaction_Date, OperationStatusId, CardlNumber, PersonId]
Index: []

## Exporting the Cleaned Dataset

In [8]:
df.to_csv("transactions_cleaned.csv", index=False, encoding="utf-8-sig")